# Site wide configuration

-title: "LINE FRIENDS"
-description: "Let LINE FRIENDS walk with us"
+title: "161013029.github.io LINE FRIENDS"
+description: "让LINE FRIENDS与我们同行"
logo: # 120x120 px default image used for Twitter summary card
teaser: # 400x250 px default teaser image used in image archive grid
-locale: en
+locale: zh_TW # 本地化翻譯
url:
feed:
  path: atom.xml

# Jekyll configuration

sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: rouge
gems:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed


# Site owner
owner:
  name: 161013029
  email: 459521563@qq.com
  twitter: FEI
  google:
    ad-client:
    ad-slot:
  -bio:
  +bio: "中山大学南方学院 文学与传媒系 网络与新媒体1班 顾菲"
  avatar: bio-photo.jpg # 160x160 px image for author byline
  disqus-shortname:


include:
  - .htaccess
exclude:
  - "*.less"
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - config
  - gulpfile.js
  - lib
  - log
  - node_modules
  - package.json
  - spec
  - tmp
